version: "3"
services:
  node:
    build: .
    image: storage-app:latest
    hostname: storage-app
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: "npm start"
    ports:
     - "6999:3001"
    restart: always

